name = "MAGEMin_app"
uuid = "3bfd43b6-b983-4998-9dd6-d5d715d830b7"
authors = ["Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashBootstrapComponents = "1b08a953-4be3-4667-9a23-fa6d05876a1e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Delaunay = "07eb4e4e-0c6d-46ef-bc4e-83d5e5d860a9"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MAGEMin_C = "e5d170eb-415a-4524-987b-12f1bce1ddab"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
T8code = "d0cc0030-9a40-4274-8435-baadcfd54fa1"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
